function new_s = red_segment( h, s, v )
% img_seg = ( h >0.81 | ( h > 0.01 & h < 0.06))&(s > 0.1)&( v > 0.15 & v <0.8 ); %old #1
img_seg = ( h >0.91 | ( h > 1e-5 & h < 0.035))&(s > 0.22)&( v > 0.15);
% img_seg = ((( h >= 0.9392 | h <= 0.040))&(s >= 0.231 & s<=1) & ( v >= 0 & v<=1));
s = regionprops(img_seg, 'BoundingBox');
new_s = cell(1,0); j = 1;
for i = 1:length(s)
    %     if s(i).BoundingBox(3) > 20 && s(i).BoundingBox(4) > 20 ...
    %             && s(i).BoundingBox(3) < 100 && s(i).BoundingBox(4) < 100 ...
    %             && s(i).BoundingBox(3)/s(i).BoundingBox(4) < 1.1 ...
    %             && s(i).BoundingBox(4)/s(i).BoundingBox(3) < 1.4
    if s(i).BoundingBox(3) > 30 && ...
            s(i).BoundingBox(4) > 30 && ...
            s(i).BoundingBox(3) < 130 && ...
            s(i).BoundingBox(4) < 130 && ...
            s(i).BoundingBox(3)/s(i).BoundingBox(4) < 1.2 && ...
            s(i).BoundingBox(4)/s(i).BoundingBox(3) < 1.2
        p_seg_img = imcrop(img_seg, s(i).BoundingBox);
        if sum(sum(p_seg_img))/(s(i).BoundingBox(3)*s(i).BoundingBox(4)) < 0.47
            new_s{j} = s(i); j = j+1;
        end
    end
end

end
